import { useState } from 'react'

import type { BillingCycleInput } from '../../api/types'

type Values = Record<'readingStart' | 'readingEnd' | 'activeConsumptionKWh' | 'injectedKWh' | 'creditsUsedKWh' | 'creditBalanceKWh' | 'totalPaidMinor' | 'flagChargeMinor', string>
const initial: Values = { readingStart: '', readingEnd: '', activeConsumptionKWh: '', injectedKWh: '', creditsUsedKWh: '', creditBalanceKWh: '', totalPaidMinor: '', flagChargeMinor: '' }
const fields: Array<[keyof Values, string, 'date' | 'number']> = [['readingStart', 'Leitura inicial', 'date'], ['readingEnd', 'Leitura final', 'date'], ['activeConsumptionKWh', 'Consumo ativo (kWh)', 'number'], ['injectedKWh', 'Energia injetada (kWh)', 'number'], ['creditsUsedKWh', 'Créditos usados (kWh)', 'number'], ['creditBalanceKWh', 'Saldo de créditos (kWh)', 'number'], ['flagChargeMinor', 'Ajuste avulso de bandeira (centavos)', 'number'], ['totalPaidMinor', 'Total pago (centavos)', 'number']]

export function BillingCycleForm({ disabled, onSave }: { disabled: boolean; onSave: (payload: BillingCycleInput) => Promise<void> }) {
  const [values, setValues] = useState(initial); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const numeric = fields.slice(2).map(([key]) => Number(values[key])); if (!values.readingStart || !values.readingEnd || numeric.some((value) => !Number.isInteger(value) || value < 0)) { setError('Preencha leituras e valores inteiros não negativos.'); return }; setSaving(true); try { await onSave({ readingStart: values.readingStart, readingEnd: values.readingEnd, activeConsumptionKWh: numeric[0], injectedKWh: numeric[1], creditsUsedKWh: numeric[2], creditBalanceKWh: numeric[3], flagChargeMinor: numeric[4], totalPaidMinor: numeric[5] }); setValues(initial) } catch { setError('Não foi possível salvar a fatura. Confira os dados e a tarifa aprovada.') } finally { setSaving(false) } }
  return <section className="billing-form"><p className="eyebrow">Conciliação local</p><h2>Registrar fatura</h2><p>Informe leituras e os seis valores da fatura. O Helio não calcula dinheiro no navegador.</p><form onSubmit={(event) => { void submit(event) }}><div className="finance-fields">{fields.map(([key, label, type]) => <label key={key}>{label}<input disabled={disabled || saving} inputMode={type === 'number' ? 'numeric' : undefined} min={type === 'number' ? 0 : undefined} onChange={(event) => setValues({ ...values, [key]: event.target.value })} required type={type} value={values[key]} /></label>)}</div>{error && <p className="form-alert" role="alert">{error}</p>}<button className="primary-action" disabled={disabled || saving} type="submit">{saving ? 'Salvando…' : 'Salvar fatura'}</button></form></section>
}
